### PR TITLE
Check for file version and improve help

### PR DESCRIPTION
**Pull request by sijnstra**
Added a check for z-machine file version as well as help to both the shell wrapper and the readme file.

### CODE REVIEW

**Review by njm64 — CHANGES_REQUESTED** [review]
Looks good! Just one issue, we lost the call to mem_init() in z.awk. We extract the header fields in hdr_init, so you could use hdr_version instead of mem[0].

**Comment by sijnstra** [comment]
Done - I think one of the side-effects of writing previous releases in hand-crafted assembler is that I'm accustomed to getting the data as directly as possible, rather than human-readable.

**Comment by njm64** [comment]
Thanks! Also it looks like we lost the mem_init() call just before txt_init().

**Comment by sijnstra** [comment]
How did that even run the last time I tested it? Regression fixed - overzealous debug removal after testing the main zawk script.

**Pull request merged**
